version: '3'
services:
  database:
   build: .
   image: database
   environment: 
    MYSQL_ROOT_USER: root
    MYSQL_ROOT_PASSWORD: Newnismo_2001
    MYSQL_DATABASE: carsdb
   volumes:
    - "./script/carsdb.sql:/docker-entrypoint-initdb.d/carsdb.sql"
   ports:
    - "3306:3306"

networks:
    default:
        external:
            name: allnetwork